### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by seif**
Mainly because I need the shovel plugin stuff from upstream

### CODE REVIEW

**Comment by doron2402** [comment]
how com I still have access to this repo :) @seif

**Comment by seif** [comment]
you have write access @doron2402 ?

**Comment by seif** [comment]
@carlf can you merge this? these are changes that were reapplied coz diff is huge https://github.com/opentable/puppetlabs-rabbitmq/commit/760a03ab70560428f50bed8e0310b94194c42921

**Comment by doron2402** [comment]
@seif LGTM :)

**Pull request closed without merging**
